import type { TaramaVerisi } from "./types";

export const mockData: TaramaVerisi = {
  dashboard: {
    profil: "Genel",
    arsivKlasoru: "Z:\\Evrak Çantası\\LucaEdefter",
    sonTarama: "2026-06-16 10:15:00",
    toplamFirma: 1,
    toplamDonem: 1,
    eksikDonem: 0,
    kritikHata: 0,
    genelSkor: 94,
    riskDagilimi: { OK: 1, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0 },
    sonOzet: [],
    ilerleme: {
      asama: "Tarama tamamlandı",
      yuzde: 100,
      islenenDosya: 18,
      toplamDosya: 18,
      bulunanMukellef: 1,
      hataSayisi: 0,
    },
    mukellefKartlari: [
      {
        id: "1234567890",
        gosterimAdi: "ÖRNEK TEKNOLOJİ A.Ş.",
        resmiUnvan: "ÖRNEK TEKNOLOJİ A.Ş.",
        vknTckn: "1234567890",
        yil: 2026,
        profil: "Genel",
        aramaMetni: "ornek teknoloji as 1234567890",
        maliMusavir: "Örnek Mali Müşavir",
        genelRisk: "OK",
        eksikDonemSayisi: 0,
        kritikSorunSayisi: 0,
        sonTarama: "2026-03-15",
        klasorYolu: "Z:\\Evrak Çantası\\LucaEdefter\\1234567890",
        donemler: Array.from({ length: 12 }, (_, index) => ({
          ayNo: `${index + 1}`.padStart(2, "0"),
          ayAd: ["Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran", "Temmuz", "Ağustos", "Eylül", "Ekim", "Kasım", "Aralık"][index],
          durumRengi: index < 1 ? "green" : "gray",
          kisaDurum: index < 1 ? "Tam" : "Yok",
          ozet: index < 1 ? "GİB onaylı berat seti mevcut." : "Bu ay için kayıt bulunmadı.",
          risk: index < 1 ? "OK" : "LOW",
          donemId: index < 1 ? "1234567890-2026-01" : "",
        })),
      },
    ],
    islemGunlugu: [
      { saat: "2026-06-16 10:10:00", seviye: "INFO", mesaj: "Klasör taraması başladı." },
      { saat: "2026-06-16 10:13:00", seviye: "INFO", mesaj: "Mükellefler tespit edildi." },
      { saat: "2026-06-16 10:15:00", seviye: "INFO", mesaj: "Tarama tamamlandı." },
    ],
  },
  donemler: [
    {
      id: "1234567890-2026-01",
      firma: "ÖRNEK TEKNOLOJİ A.Ş.",
      resmiUnvan: "ÖRNEK TEKNOLOJİ A.Ş.",
      vkn: "1234567890",
      yil: 2026,
      ay: "01",
      profil: "Genel",
      aramaMetni: "ornek teknoloji as 1234567890",
      maliMusavir: "Örnek Mali Müşavir",
      gonderimTarihi: "2026-02-14",
      imzaTarihi: "2026-02-14T18:11:00",
      gibOnayTarihi: "2026-02-15",
      donemBaslangic: "2026-01-01",
      donemBitis: "2026-01-31",
      klasorYolu: "Z:\\Evrak Çantası\\LucaEdefter\\1234567890\\01.01.2026-31.12.2026\\01",
      kontroller: [
        { id: "JOURNAL_BOOK", etiket: "Yevmiye Defteri", aciklama: "Y / Yevmiye XML ve ZIP seti", durum: "Tam", xmlAdet: 1, zipAdet: 1, beklenenAdet: 2, dosyaYollari: [] },
        { id: "LEDGER_BOOK", etiket: "Kebir Defteri", aciklama: "K / Kebir XML ve ZIP seti", durum: "Tam", xmlAdet: 1, zipAdet: 1, beklenenAdet: 2, dosyaYollari: [] },
        { id: "JOURNAL_BERAT", etiket: "Yevmiye Beratı", aciklama: "YB berat dosyaları", durum: "Tam", xmlAdet: 1, zipAdet: 1, beklenenAdet: 2, dosyaYollari: [] },
        { id: "LEDGER_BERAT", etiket: "Kebir Beratı", aciklama: "KB berat dosyaları", durum: "Tam", xmlAdet: 1, zipAdet: 1, beklenenAdet: 2, dosyaYollari: [] },
        { id: "GIB_APPROVED_JOURNAL_BERAT", etiket: "GİB Yevmiye Beratı", aciklama: "GİB onaylı YB XML ve ZIP seti", durum: "Tam", xmlAdet: 1, zipAdet: 1, beklenenAdet: 2, dosyaYollari: [] },
        { id: "GIB_APPROVED_LEDGER_BERAT", etiket: "GİB Kebir Beratı", aciklama: "GİB onaylı KB XML ve ZIP seti", durum: "Tam", xmlAdet: 1, zipAdet: 1, beklenenAdet: 2, dosyaYollari: [] },
        { id: "DEFTER_RAPORU", etiket: "Defter Raporu", aciklama: "DR XML ve ZIP seti", durum: "Tam", xmlAdet: 1, zipAdet: 1, beklenenAdet: 2, dosyaYollari: [] },
      ],
      yevmiye: "Tam",
      kebir: "Tam",
      yevmiyeBerat: "Tam",
      kebirBerat: "Tam",
      gibOnayliBerat: "Tam",
      defterRaporu: "Tam",
      durum: "Tam",
      risk: "OK",
      ozet: ["GİB onaylı berat seti ve temel dosyalar tamam."],
      aksiyonlar: ["Ek işlem gerekmiyor."],
      dosyalar: [],
      topluPaketler: [],
      yardimciDosyalar: [],
      sorunlar: [],
      loglar: [{ saat: "2026-06-16 10:15:00", seviye: "INFO", mesaj: "Dönem taraması tamamlandı." }],
    },
  ],
};
